name: unit-test

on: push

jobs:
  unit-test:
    name: ${{ matrix.os }}-${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
        compiler:
        - gcc
        - llvm
        include:
        - {os: windows-latest, compiler: msvc}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: setup gcc
      if: matrix.compiler == 'gcc'
      run: |
        echo "CC=gcc" >> $GITHUB_ENV
        echo "CXX=g++" >> $GITHUB_ENV
        echo "CMAKE_GENERATOR='Unix Makefiles'" >> $GITHUB_ENV
    - name: setup clang
      if: matrix.compiler == 'llvm'
      run: |
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV
        echo "CMAKE_GENERATOR='Unix Makefiles'" >> $GITHUB_ENV
    - name: Build Targets
      run: make test
