name: unit-test

on: push

jobs:
  unit-test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: Linux, os: ubuntu-latest }
          - { name: Windows, os: windows-latest }
          - { name: Mac, os: macos-latest }
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Build Targets
        run: |
          cmake -S . -B build
          cmake --build build
      - name: Run Tests
        run: ./build/tests
